package entity;
// Generated 2015-04-24 11:08:13 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etudiant generated by hbm2java
 */
@Entity
@Table(name="ETUDIANT"
    ,schema="C##GUILLAUME"
)
public class Etudiant  implements java.io.Serializable {


     private BigDecimal idetudiant;
     private String nom;
     private String prenom;
     private String adresse;
     private String codepostal;
     private Set<Stage> stages = new HashSet<Stage>(0);

    public Etudiant() {
    }

	
    public Etudiant(BigDecimal idetudiant, String nom, String prenom, String adresse, String codepostal) {
        this.idetudiant = idetudiant;
        this.nom = nom;
        this.prenom = prenom;
        this.adresse = adresse;
        this.codepostal = codepostal;
    }
    public Etudiant(BigDecimal idetudiant, String nom, String prenom, String adresse, String codepostal, Set<Stage> stages) {
       this.idetudiant = idetudiant;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.codepostal = codepostal;
       this.stages = stages;
    }
   
     @Id 

    
    @Column(name="IDETUDIANT", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdetudiant() {
        return this.idetudiant;
    }
    
    public void setIdetudiant(BigDecimal idetudiant) {
        this.idetudiant = idetudiant;
    }

    
    @Column(name="NOM", nullable=false, length=20)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="PRENOM", nullable=false, length=30)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="ADRESSE", nullable=false, length=30)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="CODEPOSTAL", nullable=false, length=6)
    public String getCodepostal() {
        return this.codepostal;
    }
    
    public void setCodepostal(String codepostal) {
        this.codepostal = codepostal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="etudiant")
    public Set<Stage> getStages() {
        return this.stages;
    }
    
    public void setStages(Set<Stage> stages) {
        this.stages = stages;
    }




}


