package entity;
// Generated 2015-04-23 10:49:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Poste generated by hbm2java
 */
@Entity
@Table(name="POSTE"
    ,schema="C##GUILLAUME"
)
public class Poste  implements java.io.Serializable {


     private BigDecimal idposte;
     private String description;
     private Set<Superviseur> superviseurs = new HashSet<Superviseur>(0);

    public Poste() {
    }

	
    public Poste(BigDecimal idposte, String description) {
        this.idposte = idposte;
        this.description = description;
    }
    public Poste(BigDecimal idposte, String description, Set<Superviseur> superviseurs) {
       this.idposte = idposte;
       this.description = description;
       this.superviseurs = superviseurs;
    }
   
     @Id 

    
    @Column(name="IDPOSTE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdposte() {
        return this.idposte;
    }
    
    public void setIdposte(BigDecimal idposte) {
        this.idposte = idposte;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=30)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="poste")
    public Set<Superviseur> getSuperviseurs() {
        return this.superviseurs;
    }
    
    public void setSuperviseurs(Set<Superviseur> superviseurs) {
        this.superviseurs = superviseurs;
    }




}


