package entity;
// Generated 2015-04-24 11:08:13 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stage generated by hbm2java
 */
@Entity
@Table(name="STAGE"
    ,schema="C##GUILLAUME"
)
public class Stage  implements java.io.Serializable {


     private BigDecimal idstage;
     private Etudiant etudiant;
     private Entreprise entreprise;
     private Superviseur superviseur;
     private Date datedebut;
     private BigDecimal nombresemaines;
     private BigDecimal salairesemaine;

    public Stage() {
    }

	
    public Stage(BigDecimal idstage, Date datedebut, BigDecimal nombresemaines, BigDecimal salairesemaine) {
        this.idstage = idstage;
        this.datedebut = datedebut;
        this.nombresemaines = nombresemaines;
        this.salairesemaine = salairesemaine;
    }
    public Stage(BigDecimal idstage, Etudiant etudiant, Entreprise entreprise, Superviseur superviseur, Date datedebut, BigDecimal nombresemaines, BigDecimal salairesemaine) {
       this.idstage = idstage;
       this.etudiant = etudiant;
       this.entreprise = entreprise;
       this.superviseur = superviseur;
       this.datedebut = datedebut;
       this.nombresemaines = nombresemaines;
       this.salairesemaine = salairesemaine;
    }
   
     @Id 

    
    @Column(name="IDSTAGE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdstage() {
        return this.idstage;
    }
    
    public void setIdstage(BigDecimal idstage) {
        this.idstage = idstage;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDETUDIANT")
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDENTREPRISE")
    public Entreprise getEntreprise() {
        return this.entreprise;
    }
    
    public void setEntreprise(Entreprise entreprise) {
        this.entreprise = entreprise;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDSUPERVISEUR")
    public Superviseur getSuperviseur() {
        return this.superviseur;
    }
    
    public void setSuperviseur(Superviseur superviseur) {
        this.superviseur = superviseur;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEDEBUT", nullable=false, length=7)
    public Date getDatedebut() {
        return this.datedebut;
    }
    
    public void setDatedebut(Date datedebut) {
        this.datedebut = datedebut;
    }

    
    @Column(name="NOMBRESEMAINES", nullable=false, precision=22, scale=0)
    public BigDecimal getNombresemaines() {
        return this.nombresemaines;
    }
    
    public void setNombresemaines(BigDecimal nombresemaines) {
        this.nombresemaines = nombresemaines;
    }

    
    @Column(name="SALAIRESEMAINE", nullable=false, precision=22, scale=0)
    public BigDecimal getSalairesemaine() {
        return this.salairesemaine;
    }
    
    public void setSalairesemaine(BigDecimal salairesemaine) {
        this.salairesemaine = salairesemaine;
    }




}


