package entity;
// Generated 2015-04-23 11:47:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Superviseur generated by hbm2java
 */
@Entity
@Table(name="SUPERVISEUR"
    ,schema="C##GUILLAUME"
)
public class Superviseur  implements java.io.Serializable {


     private BigDecimal idsuperviseur;
     private Poste poste;
     private String nom;
     private String prenom;
     private Set<Stage> stages = new HashSet<Stage>(0);

    public Superviseur() {
    }

	
    public Superviseur(BigDecimal idsuperviseur, String nom, String prenom) {
        this.idsuperviseur = idsuperviseur;
        this.nom = nom;
        this.prenom = prenom;
    }
    public Superviseur(BigDecimal idsuperviseur, Poste poste, String nom, String prenom, Set<Stage> stages) {
       this.idsuperviseur = idsuperviseur;
       this.poste = poste;
       this.nom = nom;
       this.prenom = prenom;
       this.stages = stages;
    }
   
     @Id 

    
    @Column(name="IDSUPERVISEUR", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdsuperviseur() {
        return this.idsuperviseur;
    }
    
    public void setIdsuperviseur(BigDecimal idsuperviseur) {
        this.idsuperviseur = idsuperviseur;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPOSTE")
    public Poste getPoste() {
        return this.poste;
    }
    
    public void setPoste(Poste poste) {
        this.poste = poste;
    }

    
    @Column(name="NOM", nullable=false, length=20)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="PRENOM", nullable=false, length=30)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="superviseur")
    public Set<Stage> getStages() {
        return this.stages;
    }
    
    public void setStages(Set<Stage> stages) {
        this.stages = stages;
    }




}


